Suggest adt installation
ansible/ansible-navigator pull request #1719
Opened 2024-03-21 08:15 UTC by audgirka

Jira https://issues.redhat.com/browse/AAP-19818

2024-03-21 10:25 UTC, shatakshiiii approved these changes

2024-03-25 19:23 UTC, ssbarnea requested changes
Change to make use of the reusable macro from https://github.com/ansible/mkdocs-ansible/pull/117

2024-03-26 13:01 UTC, ssbarnea submitted a review, later dismissed

2024-03-26 14:16 UTC, ssbarnea requested changes
This is not rendering correct, look at https://ansible--662.org.readthedocs.build/projects/builder/en/662/installation/

2024-03-27 10:08 UTC, ssbarnea approved these changes

2024-03-27 10:10 UTC, merged