Set use_develop in tox.ini
ansible/ansible-navigator pull request #549
Opened 2021-08-29 16:17 UTC by pabelanger

We are using ansible to install navigator into tox, we do not need to do
this. Lets set use_develop and have tox to it for free.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

2021-08-29 17:43 UTC, webknjaz commented on tox.ini
> -skip_install = true
Don't do this. This env doesn't need navigator at all.

2021-09-01 12:23 UTC, webknjaz commented on tox.ini
```suggestion


```

2021-09-01 12:24 UTC, webknjaz commented on tox.ini
> -allowlist_externals = ansible-playbook
This needs to be recovered.

2021-09-01 12:25 UTC, webknjaz commented on tox.ini
```suggestion


```

2021-09-10 18:10 UTC, ssbarnea requested changes

2021-09-10 18:10 UTC, ssbarnea commented on tox.ini
> +skip_install = false
is this really needed? seem unrelated change

2021-09-10 18:10 UTC, ssbarnea commented on tox.ini
> -skip_install = false
also seems unrelated.

2021-12-08 22:32 UTC, cidrblock commented
@ssbarnea @webknjaz Givent he changes in the repo recently is this still needed?

2021-12-09 11:51 UTC, ssbarnea commented
There are several problems with it, one of them being that it combines at least 3 different changes. My guess is that the standalone use of pip outside tox with smoke was intended and not an accident as the intent was to see if installation with pip works. What tox does is not always the same thing as pip, especially when using develop. Also testing install outside a virtualenv is desirable as if we use only tox venvs we may fail to identify other bugs, like conflicts with system python packages.

So, I think that PR is no longer needed and I will close it but we can reopen it at any time if needed.

2021-12-09 11:51 UTC, closed without merging