Enable use of release drafter
ansible/ansible-navigator pull request #561
Opened 2021-09-01 12:18 UTC by ssbarnea

Make use of release-drafter for building release notes and computing
the next version using semver meaning of merged PRs.

This config is based on the one already used by molecule and
ansible-lint. Results can be seen at https://github.com/ansible-community/molecule/releases

The release manager still has the freedom to change the release
notes manually.

Fixes: #558

2021-09-01 12:28 UTC, webknjaz requested changes
This needs a discussion. I don't like the idea of untracked change fragments.

2021-09-01 12:38 UTC, ssbarnea commented
> This needs a discussion. I don't like the idea of untracked change fragments.

They are not really untracked, we could easily add a rule to update tracked release notes before a release. Keep in mind that this change brings us a decent level of information regarding what was included in a release, including ability to open a discussion thread on each release. It is low maintenance approach, and much better the the current zero-release notes.

We can keep the original ticket open if you want. IMHO, it is an ok tradeoff which proved to work fine for a number of years.

2021-09-01 12:42 UTC, webknjaz commented
The fragments are not tracked in Git. It's a vendor-lock on GitHub without any ability to build the change log offline.

2021-09-01 16:26 UTC, webknjaz commented
Point is that I cannot generate a changelog with a simple tox command having GitHub unavailable.

2021-09-10 17:57 UTC, ssbarnea commented
recheck

2021-09-10 18:01 UTC, ssbarnea commented
@webknjaz Please reconsider this. Lets put it from another point of view: I do not expect this to change the project process for producing changelog. I only want to get something meaningful as comment on https://github.com/ansible/ansible-navigator/releases page. Currently we have zero content there.

Argumentation that this does not make everything perfect does not help improving the situation. I propose to activate this now, until we find a replacement that fits all requirements. I prefer a progressive improvement today, than the perfect implementation that never happens to be implemented.

2021-12-08 22:31 UTC, cidrblock commented
@ssbarnea Given the flurry of work in the repo recently is this still needed?

2021-12-09 09:21 UTC, closed without merging