Adopt src code layout
ansible/ansible-navigator pull request #562
Opened 2021-09-01 12:43 UTC by ssbarnea

Fixes: #551

2021-09-02 03:56 UTC, ganeshrn approved these changes

2021-09-02 09:47 UTC, webknjaz requested changes

2021-09-02 09:47 UTC, webknjaz commented on tox.ini
> +    -d "{toxinidir}/.tox/.doctrees" \
This change is wrong, it's missing `.tmp`. Besides, it's unrelated, so submit it separately or wait for #543 to fix it.

2021-09-02 21:42 UTC, webknjaz approved these changes

2021-09-02 22:02 UTC, merged

2021-09-03 09:59 UTC, webknjaz commented
FTR we probably need to notify the current RPM spec maintainers about the structural changes. OTOH with #557, it should be easier for them to pick up a well-tested upstream spec.