Make black run under pre-commit
ansible/ansible-navigator pull request #763
Opened 2021-12-16 20:10 UTC by ssbarnea

Runs black with same options as before under pre-commit.

2021-12-16 21:47 UTC, webknjaz requested changes
I think we need to go through the voting about even having it. The current team never did that.

2022-01-19 09:13 UTC, ssbarnea commented
Moved to draft to remove it from daily reminder.

2022-01-30 23:09 UTC, cidrblock approved these changes
I find having all the linters and formatters run the same way, cleaner, and easier to maintain.

This is not an endorsement of black as a formatter in any direction, simply an agreement that this improves the current configuration.

2022-01-31 14:50 UTC, priyamsahoo approved these changes
+1 for this !

2022-02-01 13:33 UTC, webknjaz commented on .pre-commit-config.yaml
> +- repo: https://github.com/psf/black
```suggestion
- repo: https://github.com/psf/black.git
```

2022-02-01 13:33 UTC, webknjaz commented on .pre-commit-config.yaml
> +        - .
```suggestion
    - id: black
      language_version: python3
      args:
      - -v
      - --diff
      - --check
      - .
```

2022-02-01 13:44 UTC, merged

2022-02-01 14:00 UTC, cidrblock commented
@webknjaz 

"I'll keep hating black separately from this change."

Please submit a PR to have black removed from the repository if you feel strongly about it and seek a quorum approval.