POC for running mypy with multiple python versions
ansible/ansible-navigator pull request #804
Opened 2022-01-26 09:58 UTC by ssbarnea

That should be seen as an alternative to #726 that avoids cluttering
the mypy hook configuration.

Closes: https://github.com/ansible/ansible-navigator/pull/726/files

2022-01-26 12:39 UTC, webknjaz requested changes
Changing the runtime is a bad idea because it relies on the external interpreter being of a specific version. MyPy is designed to work with the AST which is runtime-agnostic as explained in #726, making this approach pointless compared to using `--python-version` properly.

2022-01-27 09:47 UTC, ssbarnea commented
> Changing the runtime is a bad idea because it relies on the external interpreter being of a specific version. MyPy is designed to work with the AST which is runtime-agnostic as explained in #726, making this approach pointless compared to using `--python-version` properly.

Read https://github.com/ansible/ansible-navigator/pull/726#issuecomment-1023010608 -- it took only a couple of hours to get a proof that mypy outcome depends on python interpreter and that CI failure came from a change originating from pre-commit.ci auto-update, not a human. A minor change that failed on zuul.

2022-01-27 19:15 UTC, webknjaz commented
> it took only a couple of hours to get a proof that mypy outcome depends on python interpreter

Look closer into that log and the PR — that commit does not contain split mypy hook changes. It's been failing prior to that improvement before the PR got merged. It only proves that there were problems before my PR and now those problems are fixed as a result.

2022-01-28 23:13 UTC, cidrblock commented
moved to draft because I believe it was implimented

2022-01-29 09:22 UTC, closed without merging